Feat/project update
indent-dev/blueprint pull request #14
Opened 2020-07-20 11:10 UTC by masaditya

https://streamable.com/aoo2k1

2020-07-21 04:38 UTC, mnindrazaka requested changes

2020-07-21 04:38 UTC, mnindrazaka commented on src/modules/LoggedIn/Project/ProjectForm.tsx
> +  }, [props]);
harusnya dependency nya cukup `props.project` aja

```suggestion
  }, [props.project]);
```

2020-07-21 04:38 UTC, mnindrazaka commented on src/modules/LoggedIn/Project/ProjectForm.tsx
> +  toggleModal: () => void;
nama props biasain pake prefix on, misal `onToggleModal`

```suggestion
  onToggleModal: () => void;
```

2020-07-21 20:22 UTC, masaditya commented
Maaf mas, masih conflict sama `master` branch. minta tolong di solve ya hehe 
*takut sama Formik wkwkw

2020-08-19 02:25 UTC, mnindrazaka approved these changes
LGTM

2020-08-19 02:27 UTC, merged