add handle change form in project form
indent-dev/blueprint pull request #9
Opened 2020-07-17 12:14 UTC by naufalyukafi

Vidio demo project dapat dilihat pada link berikut: https://streamable.com/mzxcoq

2020-07-17 12:48 UTC, masaditya approved these changes

2020-07-18 06:00 UTC, mnindrazaka requested changes

2020-07-18 06:00 UTC, mnindrazaka commented on src/modules/LoggedIn/Project/ProjectForm.tsx
> +  }
di memoize pake useCallback jangan lupa

```suggestion
  const handleChange = React.useCallback(event: React.ChangeEvent<HTMLInputElement>) => {
    setNewData({ ...newData, [event.target.name]: event.target.value })
  }, [])
```

2020-07-18 06:00 UTC, mnindrazaka commented on src/modules/LoggedIn/Project/ProjectForm.tsx
> +  const { name, description } = newData
gak perlu di destructure disini, object `newData` langsung dimasukin ke values input nya aja. Kalo gini jadinya tiap kali rerender, variable name dan description bakal selalu didefinisikan ulang, gak bagus buat performance

2020-07-18 06:00 UTC, mnindrazaka commented on src/modules/LoggedIn/Project/ProjectForm.tsx
>      })
ini langsung newData aja

2020-07-18 06:00 UTC, mnindrazaka commented on src/modules/LoggedIn/Project/ProjectForm.tsx
>    }, [projectSync, toggleModal])
dependency newData jangan lupa dimasukin

2020-07-18 06:40 UTC, mnindrazaka requested changes

2020-07-18 06:40 UTC, mnindrazaka commented on src/modules/LoggedIn/Project/ProjectForm.tsx
> +  ])
`newData` ini harusnya berupa object. Typenya bisa pake `ProjectRequest` yang dari `useProjectSync`

2020-07-18 06:55 UTC, mnindrazaka approved these changes
lgtm

2020-07-18 06:56 UTC, merged